#!/bin/bash

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "$0")" && pwd)"
SOURCE_ROOT="${LLM_PROXY_SOURCE_ROOT:-$(cd -- "$SCRIPT_DIR/../.." && pwd)}"
OUTPUT_DIR="${1:-$SOURCE_ROOT/macos-release}"
NPM_BIN="${LLM_PROXY_NPM_BIN:-$(command -v npm || true)}"

die() {
  printf 'Error: %s\n' "$*" >&2
  exit 1
}

[[ "$(uname -s)" == "Darwin" || "${LLM_PROXY_ALLOW_NON_MACOS_TEST:-}" == "1" ]] \
  || die "this release preparer only supports macOS"
[[ -n "$NPM_BIN" && -x "$NPM_BIN" ]] || die "npm was not found; install Node.js with npm before preparing a release"
[[ -f "$SOURCE_ROOT/package.json" ]] || die "required file not found: $SOURCE_ROOT/package.json"
[[ -f "$SOURCE_ROOT/dist/server/server/index.js" ]] || die "built backend not found; run pnpm run build first"
[[ -f "$SOURCE_ROOT/dist/server/server/provider.js" ]] || die "built provider entry not found; run pnpm run build first"
[[ -f "$SOURCE_ROOT/dist/ui/index.html" ]] || die "built UI not found; run pnpm run build first"
[[ ! -e "$OUTPUT_DIR" ]] || die "output directory already exists: $OUTPUT_DIR"

mkdir -p "$OUTPUT_DIR"
cp -R "$SOURCE_ROOT/dist" "$OUTPUT_DIR/dist"
cp "$SOURCE_ROOT/package.json" "$OUTPUT_DIR/package.json"
cp -R "$SOURCE_ROOT/installer" "$OUTPUT_DIR/installer"

if [[ -f "$SOURCE_ROOT/config.toml" ]]; then
  cp "$SOURCE_ROOT/config.toml" "$OUTPUT_DIR/config.toml"
fi
if [[ -f "$SOURCE_ROOT/config.example.toml" ]]; then
  cp "$SOURCE_ROOT/config.example.toml" "$OUTPUT_DIR/config.example.toml"
fi

(cd "$OUTPUT_DIR" && "$NPM_BIN" install --package-lock-only --ignore-scripts --no-audit --no-fund)

printf 'Release prepared\n'
printf '  Output: %s\n' "$OUTPUT_DIR"
printf '  Dependencies: package-lock.json generated by npm\n'
